// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwyifrnjyvvkyzwnjfrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3eWlmcm5qeXZ2a3l6d25qZnJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODg2MDAsImV4cCI6MjA2NTU2NDYwMH0.vFhT89qNiF7H4TxfSzgpFAuqC1OufZZlSO8PUfzldwE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);